const day1_stats = {
    DemiQueen: {
        name: 'Demi Queen',
        HP: 8712,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: 0,
        Holy: 0,
        Poison: 84,
        Rot: 84,
        Bleed: 112,
        Frostbite: 112,
        Sleep: 112,
        Madness: "---", 
    },
    DemiSwordmaster: {
        name: 'Demi Swordmaster',
        HP: 4761,
        Physical: 0,
        Strike: 0,
        Slash: -20,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: 50,
        Holy: 0,
        Poison: 84,
        Rot: 84,
        Bleed: 112,
        Frostbite: 112,
        Sleep: 112,
        Madness: "---", 
    },
    BellBearingHunter: {
        name: 'Bell Bearing Hunter',
        HP: 10368,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: -10,
        Magic: 40,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    GapingDragon: {
        name: 'Gaping Dragon',
        HP: 16194,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: -10,
        Fire: -15,
        Lightning: -20,
        Holy: -10,
        Poison: "---",
        Rot: "---",
        Bleed: 154,
        Frostbite: 154,
        Sleep: "---",
        Madness: "---", 
    },
    WormFace: {
        name: 'Wormface',
        HP: 7839,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 40,
        Poison: 308,
        Rot: 231,
        Bleed: 231,
        Frostbite: 231,
        Sleep: 231,
        Madness: "---", 
    },
    ValiantGargoyle: {
        name: 'Valiant Gargoyle',
        HP: 9579,
        Physical: 10,
        Strike: 0,
        Slash: 35,
        Pierce: 35,
        Magic: 20,
        Fire: 40,
        Lightning: 40,
        Holy: 40,
        Poison: "---",
        Rot: "---",
        Bleed: "---",
        Frostbite: "---",
        Sleep: "---",
        Madness: "---",  
    },
    DearFreja: {
        name: "Duke's Dear Freja",
        HP: 7377,
        Physical: 16,
        Strike: 7,
        Slash: -10,
        Pierce: 30,
        Magic: 50,
        Fire: 30,
        Lightning: 50,
        Holy: 50,
        Poison: "---",
        Rot: 252,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---",  
    },
    NightsCavalry: {
        name: "Night's Cavalry",
        HP: 4611,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---",  
    },
    SmelterDemon: {
        name: 'Smelter Demon',
        HP: 20481,
        Physical: -10,
        Strike: -10,
        Slash: 6,
        Pierce: 8,
        Magic: 30,
        Fire: 80,
        Lightning: 30,
        Holy: 30,
        Poison: 154,
        Rot: 154,
        Bleed: "---",
        Frostbite: 252,
        Sleep: "---",
        Madness: "---",  
    },
    Commander: {
        name: 'Battle Field Commander',
        HP: 9486,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---", 
    },
    Centipede: {
        name: 'Centipede Demon',
        HP: 12297,
        Physical: 0,
        Strike: -10,
        Slash: 0,
        Pierce: 0,
        Magic: -20,
        Fire: 80,
        Lightning: -10,
        Holy: -10,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---", 
    },
    Tibia: {
        name: 'Tibia Mariner',
        HP: 9579,
        Physical: 10,
        Strike: -40,
        Slash: 10,
        Pierce: 35,
        Magic: 20,
        Fire: 20,
        Lightning: 40,
        Holy: -40,
        Poison: "---",
        Rot: 154,
        Bleed: "---",
        Frostbite: "---",
        Sleep: "---",
        Madness: "---", 
    },
    Grafted: {
        name: 'Grafted Monarch',
        HP: 14052,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---", 
    },
    Revenent: {
        name: 'Royal Revenent',
        HP: 12510,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: "---",
        Madness: "---", 
    },
    DeathKnight: {
        name: 'Death Knight',
        HP: "NA",
        Physical: 40,
        Strike: 40,
        Slash: 40,
        Pierce: 20,
        Magic: 40,
        Fire: 20,
        Lightning: 40,
        Holy: 0,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: "---",
        Madness: "---", 
    },
    Demons: {
        name: 'Demon Of Pain / From Below',
        HP: 16194,
        Physical: 0,
        Strike: 1,
        Slash: -18,
        Pierce: -2,
        Magic: 20,
        Fire: 78,
        Lightning: 22,
        Holy: 17,
        Poison: "---",
        Rot: 542,
        Bleed: 252,
        Frostbite: "---",
        Sleep: "---",
        Madness: "---", 
    },
}

export default day1_stats