const day1And2Stats = {
    DemiQueen: {
        name: 'Demi Queen',
        HP: 8712,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: 0,
        Holy: 0,
        Poison: 84,
        Rot: 84,
        Bleed: 112,
        Frostbite: 112,
        Sleep: 112,
        Madness: "Immune", 
    },
    DemiSwordmaster: {
        name: 'Demi Swordmaster',
        HP: 4761,
        Physical: 0,
        Strike: 0,
        Slash: -20,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: 50,
        Holy: 0,
        Poison: 84,
        Rot: 84,
        Bleed: 112,
        Frostbite: 112,
        Sleep: 112,
        Madness: "Immune", 
    },
    BellBearingHunter: {
        name: 'Bell Bearing Hunter',
        HP: 10368,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: -10,
        Magic: 40,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "Immune", 
    },
    GapingDragon: {
        name: 'Gaping Dragon',
        HP: 16194,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: -10,
        Fire: -15,
        Lightning: -20,
        Holy: -10,
        Poison: "Immune",
        Rot: "Immune",
        Bleed: 154,
        Frostbite: 154,
        Sleep: "Immune",
        Madness: "Immune", 
    },
    WormFace: {
        name: 'Wormface',
        HP: 7839,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 40,
        Poison: 308,
        Rot: 231,
        Bleed: 231,
        Frostbite: 231,
        Sleep: 231,
        Madness: "Immune", 
    },
    ValiantGargoyle: {
        name: 'Valiant Gargoyle',
        HP: 9579,
        Physical: 10,
        Strike: 0,
        Slash: 35,
        Pierce: 35,
        Magic: 20,
        Fire: 40,
        Lightning: 40,
        Holy: 40,
        Poison: "Immune",
        Rot: "Immune",
        Bleed: "Immune",
        Frostbite: "Immune",
        Sleep: "Immune",
        Madness: "Immune",  
    },
    DearFreja: {
        name: "Duke's Dear Freja",
        HP: 7377,
        Physical: 16,
        Strike: 7,
        Slash: -10,
        Pierce: 30,
        Magic: 50,
        Fire: 30,
        Lightning: 50,
        Holy: 50,
        Poison: "Immune",
        Rot: 252,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "Immune",
        Madness: "Immune",  
    },
    Fulghor: {
        name: 'Fulghor',
        HP: 35682,
        Physical: 0,
        Strike: 0,
        Slash: -0,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: -20,
        Holy: 30,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "Immune",  
    },
    Caligo: {
        name: 'Caligo',
        HP: 36024,
        Physical: 0,
        Strike: -15,
        Slash: 15,
        Pierce: 10,
        Magic: 20,
        Fire: -35,
        Lightning: 20,
        Holy: 20,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 524,
        Sleep: 524,
        Madness: "Immune",  
    },
    Heolster: {
        name: 'Heolster',
        HP: 36024,
        Physical: 0,
        Strike: -15,
        Slash: 15,
        Pierce: 10,
        Magic: 20,
        Fire: -35,
        Lightning: 20,
        Holy: 20,
        Poison: "Immune",
        Rot: 252,
        Bleed: "Immune",
        Frostbite: "Immune",
        Sleep: 542,
        Madness: "Immune", 
    },
}

export default day1And2Stats