const day2_stats = {
    Margit: {
        name: 'Fell Omen',
        HP: 18144,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 252,
        Madness: "---", 
    },
    Sentinel: {
        name: 'Tree Sentinel',
        HP: 13203,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 20,
        Fire: 40,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Dragon: {
        name: 'Ancient Dragon',
        HP: 20856,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 40,
        Lightning: 80,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---", 
    },
    Crucible: {
        name: 'Crucible Knight',
        HP: 8796,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 35,
        Magic: 40,
        Fire: 20,
        Lightning: 20,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 542,
        Frostbite: 252,
        Sleep: 252,
        Madness: "---", 
    },
    Hippo: {
        name: 'Crucible Knight',
        HP: 12960,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: -20,
        Holy: 0,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---", 
    },
    Commander: {
        name: 'Outland Commander',
        HP: 16797,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---", 
    },
    Wyrm: {
        name: 'Great Wyrm',
        HP: 26511,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 80,
        Lightning: 40,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 542,
        Sleep: 112,
        Madness: "---", 
    },
}