const day2_stats = {
    Margit: {
        name: 'Fell Omen',
        HP: 18144,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 252,
        Madness: "---", 
    },
    Sentinel: {
        name: 'Tree Sentinel',
        HP: 13203,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 20,
        Fire: 40,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Dragon: {
        name: 'Ancient Dragon',
        HP: 20856,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 40,
        Lightning: 80,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---", 
    },
    Crucible: {
        name: 'Crucible Knight',
        HP: 8796,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 35,
        Magic: 40,
        Fire: 20,
        Lightning: 20,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 542,
        Frostbite: 252,
        Sleep: 252,
        Madness: "---", 
    },
    Hippo: {
        name: 'Golden Hippo',
        HP: 12960,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 0,
        Fire: -20,
        Lightning: -20,
        Holy: 0,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: "---", 
    },
    Commander: {
        name: 'Outland Commander',
        HP: 16797,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---", 
    },
    Wyrm: {
        name: 'Great Wyrm',
        HP: 26511,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 80,
        Lightning: 40,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 542,
        Sleep: 112,
        Madness: "---", 
    },
    Nox: {
        name: 'Dragonkin Soldier',
        HP: 22338,
        Physical: 10,
        Strike: 0,
        Slash: 0,
        Pierce: 10,
        Magic: 20,
        Fire: 20,
        Lightning: 40,
        Holy: 20,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 542,
        Sleep: 112,
        Madness: "---", 
    },
    Draconic: {
        name: 'Draconic Tree Sentinel',
        HP: 13227,
        Physical: 10,
        Strike: 10,
        Slash: 25,
        Pierce: 10,
        Magic: 20,
        Fire: 40,
        Lightning: 40,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Fallingstar: {
        name: 'Fallingstar Beast',
        HP: 18807,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 35,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: "---",
        Sleep: "---",
        Madness: "---", 
    },
    Apostle: {
        name: 'Godskin Apostle (Skinny)',
        HP: 10957,
        Physical: 0,
        Strike: 10,
        Slash: -10,
        Pierce: 0,
        Magic: 20,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 112,
        Frostbite: 154,
        Sleep: 112,
        Madness: "---", 
    },
    Noble: {
        name: 'Godskin Apostle (Fatty)',
        HP: 13372,
        Physical: 0,
        Strike: 35,
        Slash: 10,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 112,
        Frostbite: 154,
        Sleep: 112,
        Madness: "---", 
    },
    Bird: {
        name: 'Death Rite Bird',
        HP: 16983,
        Physical: 10,
        Strike: -40,
        Slash: 10,
        Pierce: 35,
        Magic: 20,
        Fire: 20,
        Lightning: 40,
        Holy: -40,
        Poison: "---", 
        Rot: 253,
        Bleed: "---", 
        Frostbite: "---", 
        Sleep: "---", 
        Madness: "---", 
    },
    NamelessBird: {
        name: 'Nameless King (Dragon)',
        HP: 6633,
        Physical: 20,
        Strike: 18,
        Slash: 21,
        Pierce: 2,
        Magic: 10,
        Fire: 35,
        Lightning: -31,
        Holy: 0,
        Poison: 252, 
        Rot: 253,
        Bleed: 252, 
        Frostbite: 154, 
        Sleep: "---", 
        Madness: "---", 
    },
    Nameless: {
        name: 'Nameless King',
        HP: 16983,
        Physical: 20,
        Strike: 18,
        Slash: 21,
        Pierce: 2,
        Magic: 10,
        Fire: 35,
        Lightning: -31,
        Holy: 0,
        Poison: 252, 
        Rot: 253,
        Bleed: 252, 
        Frostbite: 154, 
        Sleep: "---", 
        Madness: "---", 
    },
    Dancer: {
        name: 'Dancer of Boreal Valley',
        HP: 14514,
        Physical: 20,
        Strike: 19,
        Slash: 22,
        Pierce: 20,
        Magic: 19,
        Fire: 18,
        Lightning: 17,
        Holy: -25,
        Poison: "---",  
        Rot: 252,
        Bleed: 252, 
        Frostbite: "---", 
        Sleep: "---", 
        Madness: "---", 
    },
    Knight: {
        name: 'Knight Artorias',
        HP: "NA",
        Physical: 0,
        Strike: -10,
        Slash: 10,
        Pierce: 0,
        Magic: 15,
        Fire: 10,
        Lightning: -10,
        Holy: -10,
        Poison: 543,  
        Rot: 252,
        Bleed: 252, 
        Frostbite: 542, 
        Sleep: "---", 
        Madness: "---", 
    }
}

export default day2_stats