const major_stats = {
    Flying: {
        name: 'Flying Dragon',
        HP: 9109,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 40,
        Lightning: 40,
        Holy: 40,
        Poison: 252,  
        Rot: 252,
        Bleed: 252, 
        Frostbite: 252, 
        Sleep: "---", 
        Madness: "---", 
    },
    Ulcerated: {
        name: 'Ulcerated Tree Spirit',
        HP: 17127,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: 20,
        Fire: -20,
        Lightning: 20,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 112,
        Sleep: "---",
        Madness: "---", 
    },
    BellBearingHunter: {
        name: 'Bell Bearing Hunter',
        HP: 14156,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: -10,
        Magic: 40,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Avatar: {
        name: 'Erdtree Avatar',
        HP: 13928,
        Physical: 35,
        Strike: 35,
        Slash: 35,
        Pierce: -10,
        Magic: 40,
        Fire: 40,
        Lightning: 20,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Ancestor: {
        name: 'Ancestor Spirit',
        HP: 11294,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 20,
        Fire: -20,
        Lightning: 0,
        Holy: -20,
        Poison: 542,
        Rot: 542,
        Bleed: 542,
        Frostbite: 542,
        Sleep: "---", 
        Madness: "---", 
    },
    Sentinel: {
        name: 'Tree Sentinel',
        HP: 12199,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 20,
        Fire: 40,
        Lightning: 0,
        Holy: 40,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Wyrm: {
        name: 'Great Wyrm',
        HP: 16083,
        Physical: 10,
        Strike: 10,
        Slash: 35,
        Pierce: 10,
        Magic: 40,
        Fire: 80,
        Lightning: 40,
        Holy: 40,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 542,
        Sleep: 112,
        Madness: "---", 
    },
    Loretta: {
        name: "Royal Carian Knight",
        HP: 16083,
        Physical: 10,
        Strike: 10,
        Slash: 10,
        Pierce: 10,
        Magic: 40,
        Fire: 40,
        Lightning: 0,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
    Bird: {
        name: 'Death Rite Bird',
        HP: 16983,
        Physical: 10,
        Strike: -40,
        Slash: 10,
        Pierce: 35,
        Magic: 20,
        Fire: 20,
        Lightning: 40,
        Holy: -40,
        Poison: "---", 
        Rot: 253,
        Bleed: "---", 
        Frostbite: "---", 
        Sleep: "---", 
        Madness: "---", 
    },
    BBK: {
        name: 'Black Blade Kindred',
        HP: 10471,
        Physical: 10,
        Strike: 0,
        Slash: 35,
        Pierce: 35,
        Magic: 20,
        Fire: 40,
        Lightning: 40,
        Holy: 80,
        Poison: "---", 
        Rot: "---",
        Bleed: "---", 
        Frostbite: "---", 
        Sleep: "---", 
        Madness: "---", 
    },
    Draconic: {
        name: 'Draconic Tree Sentinel',
        HP: 13948,
        Physical: 10,
        Strike: 10,
        Slash: 25,
        Pierce: 10,
        Magic: 20,
        Fire: 40,
        Lightning: 40,
        Holy: 20,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: 154,
        Madness: "---", 
    },
}

export default major_stats