const minor_stats = {
    scion: {
        name: 'Grafted Scion',
        HP: 5446,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,  
        Rot: 154,
        Bleed: 112, 
        Frostbite: 112, 
        Sleep: 112, 
        Madness: "---", 
    },
    black: {
        name: 'Black Knife Assassin',
        HP: 2718,
        Physical: 10,
        Strike: 10,
        Slash: 10,
        Pierce: 35,
        Magic: 20,
        Fire: 20,
        Lightning: 20,
        Holy: 40,
        Poison: "---",  
        Rot: "---",  
        Bleed: "---",   
        Frostbite: 154, 
        Sleep: "---", 
        Madness: "---", 
    },
    wolf: {
        name: 'Red Wolf',
        HP: 3504,
        Physical: 10,
        Strike: 0,
        Slash: -10,
        Pierce: 35,
        Magic: 40,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,  
        Rot: 154,
        Bleed: 252, 
        Frostbite: 252, 
        Sleep: 154, 
        Madness: "---", 
    },
    zamor: {
        name: 'Hero of Zamor',
        HP: 4264,
        Physical: 10,
        Strike: 0,
        Slash: -10,
        Pierce: 35,
        Magic: 40,
        Fire: 20,
        Lightning: 20,
        Holy: 20,
        Poison: 154,  
        Rot: 154,
        Bleed: 252, 
        Frostbite: 252, 
        Sleep: 154, 
        Madness: "---", 
    },
    leonine: {
        name: 'Leonine Misbegotten',
        HP: 3730,
        Physical: 10,
        Strike: 10,
        Slash: 0,
        Pierce: 10,
        Magic: 20,
        Fire: 0,
        Lightning: 20,
        Holy: 20,
        Poison: 154,  
        Rot: 154,
        Bleed: 154, 
        Frostbite: 154, 
        Sleep: 154, 
        Madness: "---", 
    },
    elder: {
        name: 'Elder Lion',
        HP: 3464,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 10,
        Magic: 0,
        Fire: -20,
        Lightning: 0,
        Holy: 0,
        Poison: 154,  
        Rot: 154,
        Bleed: 252, 
        Frostbite: 252, 
        Sleep: 112, 
        Madness: "---", 
    },
    hippo: {
        name: 'Golden Hippo',
        HP: 3464,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 10,
        Magic: 0,
        Fire: -20,
        Lightning: 0,
        Holy: 0,
        Poison: 154,  
        Rot: 154,
        Bleed: 252, 
        Frostbite: 252, 
        Sleep: 112, 
        Madness: "---", 
    }
}