const nightlordStats = {
    Gladius: {
        name: 'Gladius (Tricephalos)',
        HP: 33984,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: -10,
        Magic: 0,
        Fire: 50,
        Lightning: 0,
        Holy: -35,
        Poison: 542,
        Rot: 252,
        Bleed: 252,
        Frostbite: 542,
        Sleep: 154,
        Madness: "---", 
    },
    Adel: {
        name: 'Adel (Gaping Jaw)',
        HP: 39420,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: 0,
        Fire: 20,
        Lightning: 50,
        Holy: 0,
        Poison: 154,
        Rot: 154,
        Bleed: 542,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---", 
    },
    Gnoster: {
        name: 'Gnoster (Sentient Pest)',
        HP: 39081,
        Physical: -15,
        Strike: -15,
        Slash: -25,
        Pierce: -25,
        Magic: 50,
        Fire: -40,
        Lightning: 10,
        Holy: 10,
        Poison: 542,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 542,
        Madness: "---", 
    },
    Faurtis: {
        name: 'Faurtis (Sentient Pest)',
        HP: 39081,
        Physical: 10,
        Strike: -20,
        Slash: 20,
        Pierce: -10,
        Magic: 10,
        Fire: -35,
        Lightning: 10,
        Holy: 10,
        Poison: 252,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 542,
        Madness: "---", 
    },
    Animus: {
        name: 'Animus (Sentient Pest)',
        HP: 39081,
        Physical: 0,
        Strike: 0,
        Slash: 0,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: 0,
        Holy: 0,
        Poison: "---",
        Rot: "---",
        Bleed: "---",
        Frostbite: "---",
        Sleep: "---",
        Madness: "---",  
    },
    Maris: {
        name: 'Maris (Augur)',
        HP: 38061,
        Physical: 0,
        Strike: 20,
        Slash: -15,
        Pierce: 10,
        Magic: 20,
        Fire: 50,
        Lightning: -40,
        Holy: 15,
        Poison: "---",
        Rot: 252,
        Bleed: "---",
        Frostbite: 252,
        Sleep: "---",
        Madness: "---",  
    },
    Libra: {
        name: 'Libra (Equilibrius Beast)',
        HP: 39144,
        Physical: 0,
        Strike: 0,
        Slash: -10,
        Pierce: 0,
        Magic: 20,
        Fire: -20,
        Lightning: 0,
        Holy: -35,
        Poison: 154,
        Rot: 154,
        Bleed: 252,
        Frostbite: 252,
        Sleep: "---",
        Madness: 154,  
    },
    Fulghor: {
        name: 'Fulghor (Darkdrift Knight)',
        HP: 35682,
        Physical: 0,
        Strike: 0,
        Slash: -0,
        Pierce: 0,
        Magic: 0,
        Fire: 0,
        Lightning: -20,
        Holy: 30,
        Poison: 154,
        Rot: 154,
        Bleed: 154,
        Frostbite: 154,
        Sleep: 154,
        Madness: "---",  
    },
    Caligo: {
        name: 'Caligo (Fissure in the Fog)',
        HP: 36024,
        Physical: 0,
        Strike: -15,
        Slash: 15,
        Pierce: 10,
        Magic: 20,
        Fire: -35,
        Lightning: 20,
        Holy: 20,
        Poison: 252,
        Rot: 252,
        Bleed: 252,
        Frostbite: 524,
        Sleep: 524,
        Madness: "---",  
    },
    Heolster: {
        name: 'Heolster (Night Aspect)',
        HP: 36024,
        Physical: 0,
        Strike: -15,
        Slash: 15,
        Pierce: 10,
        Magic: 20,
        Fire: -35,
        Lightning: 20,
        Holy: 20,
        Poison: "---",
        Rot: 252,
        Bleed: "---",
        Frostbite: "---",
        Sleep: 542,
        Madness: "---", 
    },
}

export default nightlordStats